mysite/urls.py
# """mysite URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
# from .import views




urlpatterns = [
    path('admin/', admin.site.urls),
    # path('polls/', include('polls.urls')),
    path('',include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('home/',TemplateView.as_view(template_name='dashboard/home.html'),name='home'),


    # path('profile',views.profile,name='profile')



    # path('accounts/', include('django.contrib.auth.urls')),

]

polls/urls.py
from django.urls import path

from . import views
from .views import APPUpdateView

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('hello/',views.Hello.as_view(),name='hello'),
    path('update/<int:id>/', APPUpdateView.as_view(),name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.





class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
     
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
class ques(models.Model):
    quest=models.CharField(max_length=200)

polls/views.py

from django.shortcuts import render,redirect
from django.template import loader
from django.urls import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views import generic, View
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Question,Choice
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic.edit import UpdateView
from django.db import models
from .models import ques


# class LoginView(LoginView):
#     template_name = 'LoginView.html
# Create your views here.
@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    # key = ques.objects.all().order_by('-updated')
    # context = {'key': key}
    #
    # return render(request,'polls/index.html',context)


    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        # key = ques.objects.all()
        # return Question.objects.filter(
        #     pub_date__lte=timezone.now()
        #  ).order_by('-pub_date')[:5]
        return ques.objects.all()

    # def get(self,request):
    #     key = ques.objects.all().order_by('-updated')
    #     context = {'key': key}
    #
    #     return render(request, 'polls/index.html', context)






class DetailView(generic.DetailView):
    ...
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class Hello(View):

    def get(self,request):

        return render(request,'polls/hello.html')

    def post(self,request):


        quest=request.POST.get('quest')
        ques(quest=quest).save()
        print("********")
        # return HttpResponseRedirect("/")
        # return render(request,'polls/hello.html')

        return redirect('/polls/')

    # def edit(request, id):
    #     context = ques.objects.get(id=id)
    #
    #     return render(request, 'edit.html', {'context': context})

class APPUpdateView(View):
    # model =ques
    # fields = [
    #    "quest"
    # ]
    def get(self,request,id):
        a = ques.objects.get(id=id)
        return render(request,'polls/edit.html',{'a':a})
    def post(self,request,id):
        a = ques.objects.get(id=id)
        a.quest = request.POST.get('quest')
        a.save()
        return redirect('/polls/')

def delete(request,id):
   b= ques.objects.get(id=id)
   b.delete()
   return redirect('/polls/')









polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
     <h1>Question</h1>
  <form action="/polls/update/{{ a.id }}/" method="post">
       {% csrf_token %}
  <label for="quest">Add a Question</label><br>
  <input type="text" id="quest" name="quest"value="{{ a.quest }}"><br>
      <input type="submit" value="Save">
     </form>
</body>
</html>

polls/templates/polls/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <h1>Question</h1>
  <form method="post">
       {% csrf_token %}
  <label for="quest">Add a Question</label><br>
  <input type="text" id="quest" name="quest"><br>
      <button type="submit">submit</button>
     </form>
</body>
</html>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
<!--    <ul>-->
<!--    {% for question in latest_question_list %}-->
<!--    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->
<!--         <a href="{% url 'polls:update' question.id %}">update</a>-->
<!--    {% endfor %}-->
<!--    </ul>-->
{% else %}
    <p>No polls are available.</p>
{% endif %}
<a href ="{% url 'logout' %}">logout</a>
<a href="{% url 'polls:hello' %}">button</a>
<table>
  <tr>
    <th>id</th>
    <th>questions</th>

  </tr>
</table>

{% for question in latest_question_list %}
{{question.id}}
{{question.quest}}
<a href="{% url 'polls:update' question.id %}">update</a><br>
</button><a href="{% url 'polls:delete' question.id %}">delete</a><br>

{% endfor %}
<!-- <button style="back-groundcolor:red;" type="edit"></a> Edit</button>-->
<!--{% for i in keys %}-->
<!--{{i.id}}-->
<!--{{i.quest}}-->
<!--{% endfor %}-->


polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>